import os
import time
import pickle
from Crypto.Cipher import AES
from Crypto.Util.Padding import pad

def main():
    text=input("enter the text to be encrypted: ")
    print("\n")
    print("caesor encryption")
    time.sleep(2)
    key_1=int(input("enter the key,any number between 1 and 9: "))
    if(key_1<1 or key_1>9):
        print("only number between 1 and 9 is accepted")
    else:
        print("encrypting text....")
        time.sleep(3)
        encrypted_1=""
        for i in text:
            encrypted_1=encrypted_1+chr(ord(i)+key_1)
        print("caesor encryption successful")
        print("encrypted text:",encrypted_1)
        print("\n")
        print("adding key to ciphertext_1.txt...")
        time.sleep(3)
        file1=open("ciphertext_1.txt","w")
        file1.write(str(key_1))
        file1.close()
        print("\n")
    print("AES encryption")
    time.sleep(2)
    key_2=os.urandom(16)
    iv=os.urandom(16)
    print("key generated by the program: ",key_2)
    print("initialisation vector generated by the program: ",iv)
    print("encrypting text....")
    time.sleep(3)
    encoded_text=encrypted_1.encode()
    padded_text=pad(encoded_text,16)
    aes=AES.new(key_2,AES.MODE_CBC,iv)
    encrypted_2=aes.encrypt(padded_text)
    print("AES encryption successful")
    print("encrypted text: ",encrypted_2)
    print("\n")
    print("adding data to ciphertext_2.dat")
    time.sleep(3)
    file=open("ciphertext_2.dat","wb")
    pickle.dump(encrypted_2,file)
    pickle.dump(key_2,file)
    pickle.dump(iv,file)
    file.close()
    print("encrypted text,key and iv added to ciphertext_2.dat file")

if __name__=="__main__":
    main()